name: edupresence

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
    description: Run static analysis

  format:
    exec: dart format .
    description: Format Dart code

  clean:
    exec: flutter clean
    description: Clean build files

  build:android:
    exec: cd apps/edupresence_mobile && flutter build apk --release
    description: Build Android app

  build:windows:
    exec: cd apps/edupresence_desktop && flutter build windows --release
    description: Build Windows app

  generate:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: Generate code for all packages

  test:
    exec: flutter test
    description: Run tests

  test:coverage:
    # Run tests with coverage and generate LCOV report
    exec: flutter test --coverage && lcov --remove coverage/lcov.info '**/*.g.dart' '**/*.freezed.dart' -o coverage/lcov.info
    description: Run tests with coverage

  version:
    # Bump version in pubspec.yaml files
    exec: |
      dart pub global activate pubspec_version
      dart pub global run pubspec_version:set $1
    description: Update version number (usage - melos run version 1.0.0)

  release:prepare:
    # Prepare for release - run tests, generate code, etc
    exec: |
      melos run clean
      melos bootstrap
      melos run generate
      melos run analyze
      melos run test:coverage
    description: Prepare for release by running all checks