name: edupresence

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
    description: Run static analysis

  format:
    exec: dart format .
    description: Format Dart code

  clean:
    exec: flutter clean
    description: Clean build files

  build:android:
    exec: cd apps/edupresence_mobile && flutter build apk
    description: Build Android app

  build:windows:
    exec: cd apps/edupresence_desktop && flutter build windows
    description: Build Windows app

  generate:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: Generate code for all packages

  test:
    exec: flutter test
    description: Run tests