include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_dynamic_calls: ignore
  exclude:
    [build/**, lib/**.freezed.dart, lib/**.g.dart]

  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false