name: edupresence_core
description: Core package for EduPresence containing models, repositories, and providers.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  edupresence_supabase:
    path: ../edupresence_supabase
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  very_good_analysis: ^6.0.0
