name: edupresence_core
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.8.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0
