name: edupresence_supabase
description: Supabase client package for EduPresence.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter
  riverpod: ^2.5.1
  supabase_flutter: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
