name: edupresence_ui
description: UI components package for EduPresence
version: 0.1.0
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  edupresence_core: 0.1.0
  fluent_ui: ^4.8.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  very_good_analysis: ^5.1.0